import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from 'jotai'
import { auth } from "../auth"
import { signIn, signOut } from "@/auth"
import Header from "@/app/header"
import Image from "next/image"
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className + " max-w-screen-xl m-auto px-4"}>
        <Provider>
          <Header session={session} />
          {children}
        </Provider>
      </body>
    </html>
  );
}
