import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from 'jotai'
import { auth } from "../auth"
import { signIn, signOut } from "@/auth"
import Image from "next/image"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={inter.className + " max-w-screen-xl m-auto"}>
        <Provider>
          <header className="flex justify-between items-center py-8">
            <h1 className="text-4xl font-bold">MagiClaw</h1>
            {
              session ? (
                <div className="flex items-center space-x-4">
                  <button className="btn btn-circle">
                    <Image alt="avatar" tabIndex={0} src={session.user?.image as string} className="rounded-full w-auto h-auto" width={48} height={48} />
                  </button>
                  <div className="flex items-center space-x-4">
                    <form
                      action={async () => {
                        "use server"
                        await signOut()
                      }}
                    >
                      <button type="submit" className="btn btn-outline">Sign Out</button>
                    </form>
                  </div>
                </div>

              ) : (
                <div className="flex items-center space-x-4">
                  <form action={async () => {
                    "use server"
                    await signIn("github")
                  }}>
                    <button className="btn btn-outline">Sign In with GitHub</button>
                  </form>
                </div>
              )
            }
          </header>
          {children}
        </Provider>
      </body>
    </html>
  );
}
